### ISSUE TITLE
我将Readme.md翻译成了中文，希望可以加进去

### ISSUE THREAD

**Issue by hslzz** [hexojs/hexo-generator-feed#232]
### Check List

- [x] I have already read README.
- [x] I have already searched existing issues.
- [x] I have already searched existing pull requrests.

### Feature Request

I translated your Readme.md into Chinese
-------------------------------------------
# hexo-generator-feed

[![构建状态](https://github.com/hexojs/hexo-generator-feed/workflows/Tester/badge.svg)](https://github.com/hexojs/hexo-generator-feed/actions?query=workflow%3ATester)
[![NPM 版本](https://badge.fury.io/js/hexo-generator-feed.svg)](https://www.npmjs.com/package/hexo-generator-feed)
[![覆盖率状态](https://img.shields.io/coveralls/hexojs/hexo-generator-feed.svg)](https://coveralls.io/r/hexojs/hexo-generator-feed?branch=master)

生成 Atom 1.0 或 RSS 2.0 订阅源。

## 安装

bash

复制

```
npm install hexo-generator-feed --save
```

版本对应关系：

- Hexo 4+：2.x
- Hexo 3：1.x
- Hexo 2：0.x

## 使用说明

在文章的 [front-matter](https://hexo.io/zh-cn/docs/front-matter) 中，可选添加 `description`、`intro` 或 `excerpt` 字段来编写文章摘要。若未设置，将默认使用文章摘要或前140个字符作为内容概要。

## 配置选项

可在 `_config.yml` 中配置插件：

```yaml
feed:
  enable: true         # 启用插件（默认启用）
  type: atom           # 订阅类型（atom/rss2）
  path: atom.xml       # 输出路径
  limit: 20            # 最大文章数（0/False 显示全部）
  hub:                 # PubSubHubbub 中心地址
  content:             # 是否包含全文内容
  content_limit: 140   # 摘要截取长度（当未设置文章摘要时）
  content_limit_delim: ' ' # 摘要截取分隔符
  order_by: -date      # 文章排序规则
  icon: icon.png       # 自定义订阅图标
  autodiscovery: true  # 开启自动发现
  template:            # 自定义模板路径
```

详细参数说明：

- **enable** - 启用/禁用插件（默认：`true`）

- **type** - 输出类型（支持 `atom` 或 `rss2`，同时生成需指定数组格式）

  yaml

  复制

  ```yaml
  feed:
    # 生成 atom 订阅
    type: atom
  
    # 同时生成两种订阅
    type:
      - atom
      - rss2
    path:
      - atom.xml
      - rss2.xml
  ```

- **path** - 输出路径（多类型时路径需与类型顺序对应，默认：atom.xml/rss2.xml）

- **limit** - 显示文章数量上限（`0` 或 `false` 表示无限制）

- **hub** - PubSubHubbub 服务地址（不使用请留空）

- **content** - 是否在订阅中包含完整文章内容（默认：仅摘要）

- **content_limit** - 自动摘要长度（当未设置文章描述时生效）

- **content_limit_delim** - 摘要截断分隔符（在指定长度前寻找最后一个分隔符进行截断）

- **order_by** - 文章排序规则（默认：`-date` 按日期倒序）

- **icon** - 自定义订阅图标（默认使用主配置中的邮箱Gravatar）

- **autodiscovery** - 添加[订阅自动发现](https://www.rssboard.org/rss-autodiscovery)标签（默认：`true`）

  - 注意：部分主题已内置此功能，禁用时需同步调整主题配置

- **template** - 自定义模板路径（可参考默认模板：[atom.xml](https://atom.xml/) 和 [rss2.xml](https://rss2.xml/)）

  yaml

  复制

  ```yaml
  #（可选）排除自定义模板被复制到 public/ 目录
  # 或在模板文件名前添加下划线，如：_custom.xml
  # 详见：https://hexo.io/zh-cn/docs/configuration#包含或排除文件/文件夹
  exclude:
    - 'custom.xml'
  feed:
    type:
      - atom
      - rss2
    template:
      - ./source/custom.xml
    # atom 将使用 custom.xml 生成
    # rss2 仍使用默认模板生成
  ```

### Additional context

[Readme_cn.md](https://github.com/user-attachments/files/19407350/Readme_cn.md)
