### ISSUE TITLE
Support rss2 and atom at the same time.

### ISSUE THREAD

**Issue by mythsman** [hexojs/hexo-generator-feed#59]
Well , i want my website provides the two types at the same time, can anyone do me a favour?

**Comment by curbengh** [comment]
@mythsman 

I've drafted something to support this feature.
How to test:

``` diff
package.json
-  "hexo-generator-feed": "^2.0.0"
+  "hexo-generator-feed": "curbengh/hexo-generator-feed#atom-rss2"
```

``` yml
_config.yml
feed:
  type:
    - 'atom'
    - 'rss2'
  autodiscovery: false # currently not compatible yet
```
